/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://dfv4gunctzfs3nrhi2fthqhq6u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h2wum7wqwnbanispy45vrq7y5u",
    "aws_cognito_identity_pool_id": "us-east-1:cb2a9a3f-0a6d-40da-80f4-5e55d6be7e05",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_urC2NN63c",
    "aws_user_pools_web_client_id": "78s0mtdlnlerbq42an2nv6rhre",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
